# Generated by Django 5.2.16 on 2026-07-15 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_name"),
        ("catalog", "0005_deck_anki_deck_name"),
        ("notes", "0002_note_anki_deck_path_notetype_structure_changed_at_and_more"),
        ("suggestions", "0005_suggestion_note_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("suggestion_accepted", "Suggestion Accepted"),
                            ("suggestion_rejected", "Suggestion Rejected"),
                            ("new_suggestion", "New Suggestion"),
                            ("sync_pending", "Sync Pending"),
                        ],
                        max_length=19,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="catalog.deck",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notes.note",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.user",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="suggestions.suggestion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "created_at"],
                        name="notif_recipient_unread_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("resolved_at__isnull", True), ("type", "sync_pending")
                        ),
                        fields=("recipient", "deck"),
                        name="unique_active_sync_pending_per_recipient_deck",
                    )
                ],
            },
        ),
    ]
