# Generated by Django 5.2.16 on 2026-07-13 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="note_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decks",
                to="notes.notetype",
            ),
        ),
        migrations.AddField(
            model_name="deckmoderator",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderators",
                to="catalog.deck",
            ),
        ),
        migrations.AddField(
            model_name="deckmoderator",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="deckmoderator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderated_decks",
                to="accounts.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="deckmoderator",
            constraint=models.UniqueConstraint(
                fields=("deck", "user"), name="unique_deck_moderator"
            ),
        ),
    ]
