# Generated by Django 5.2.16 on 2026-07-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='note_type',
        ),
    ]
