# Generated by Django 5.2.16 on 2026-07-14 23:08

from django.db import migrations, models


def backfill_anki_deck_name(apps, schema_editor):
    Deck = apps.get_model("catalog", "Deck")
    for deck in Deck.objects.all():
        deck.anki_deck_name = deck.name
        deck.save(update_fields=["anki_deck_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_deck_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='anki_deck_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_anki_deck_name, migrations.RunPython.noop),
    ]
