# Generated by Django 5.2.16 on 2026-07-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_deck_anki_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
