# Generated by Django 5.2.16 on 2026-07-13 01:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("field_names", models.JSONField(default=list)),
                ("templates", models.JSONField(default=list)),
                ("css", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_values", models.JSONField(default=dict)),
                ("tags", models.JSONField(default=list)),
                ("guid", models.CharField(max_length=64)),
                ("mod", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="catalog.deck",
                    ),
                ),
                (
                    "note_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="notes.notetype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["deck", "mod"], name="notes_note_deck_id_13caa8_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deck", "guid"), name="unique_note_guid_per_deck"
                    )
                ],
            },
        ),
    ]
