# Generated by Django 5.2.16 on 2026-07-13 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auth_id", models.UUIDField(unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "target_career",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fiscal", "Fiscal"),
                            ("policial", "Policial"),
                            ("juridica", "Juridica"),
                            ("outra", "Outra"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "target_board",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("consent_marketing_emails", models.BooleanField(default=False)),
                ("consent_research_data", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
