# Generated by Django 5.2.16 on 2026-07-13 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0002_note_anki_deck_path_notetype_structure_changed_at_and_more'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.user')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='suggestions.suggestion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', False), ('suggestion__isnull', True)), models.Q(('note__isnull', True), ('suggestion__isnull', False)), _connector='OR'), name='comment_note_xor_suggestion')],
            },
        ),
    ]
