# Generated by Django 5.2.16 on 2026-07-13 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0003_subscription"),
        ("notes", "0002_note_anki_deck_path_notetype_structure_changed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("change", "Change"),
                            ("new_note", "New Note"),
                            ("deletion", "Deletion"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "change_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conteudo_atualizado", "Conteúdo atualizado"),
                            ("ortografia_gramatica", "Ortografia/Gramática"),
                            ("erro_conteudo", "Erro de conteúdo"),
                            ("nova_tag", "Nova tag"),
                            ("tag_atualizada", "Tag atualizada"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("justification", models.TextField()),
                ("proposed_field_values", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="accounts.user",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="catalog.deck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuggestionTargetNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_targets",
                        to="notes.note",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_notes",
                        to="suggestions.suggestion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="suggestion",
            index=models.Index(
                fields=["deck", "status"], name="suggestions_deck_id_bdcbd9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestiontargetnote",
            constraint=models.UniqueConstraint(
                fields=("suggestion", "note"), name="unique_suggestion_target_note"
            ),
        ),
    ]
