# Generated by Django 5.2.16 on 2026-07-13 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='suggestions.suggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_votes', to='accounts.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('suggestion', 'user'), name='unique_vote_per_user')],
            },
        ),
    ]
