# Generated by Django 5.2.16 on 2026-07-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_anki_deck_path_notetype_structure_changed_at_and_more'),
        ('suggestions', '0004_alter_suggestion_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='note_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='notes.notetype'),
        ),
    ]
